# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-15 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='is_tj',
            field=models.BooleanField(default=False, verbose_name='是否推荐'),
        ),
    ]
