# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-03 11:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('Create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('hcity', models.CharField(blank=True, max_length=50, null=True, verbose_name='省')),
                ('hproper', models.CharField(blank=True, max_length=50, null=True, verbose_name='市')),
                ('harea', models.CharField(max_length=50, verbose_name='区')),
                ('detail', models.CharField(max_length=255, verbose_name='详细地址')),
                ('username', models.CharField(max_length=100, verbose_name='收货人姓名')),
                ('phone', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator('^1[3-9]\\d{9}$', '手机号码格式错误')], verbose_name='收货人手机号')),
                ('isDefault', models.BooleanField(default=False, verbose_name='是否为默认地址')),
            ],
            options={
                'verbose_name': '收货地址管理',
                'verbose_name_plural': '收货地址管理',
                'db_table': 'sp_address',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_delete', models.BooleanField(default=False)),
                ('Create_time', models.DateField(auto_now_add=True)),
                ('update_time', models.DateField(auto_now=True)),
                ('username', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11, '手机号至少11位')], verbose_name='用户名,使用手机号')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('my_name', models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.MinLengthValidator(2, '用户昵称至少2位')], verbose_name='用户昵称')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别选择,默认男')),
                ('my_birthday', models.DateField(blank=True, null=True, verbose_name='用户生日,默认为空')),
                ('school', models.CharField(blank=True, max_length=50, null=True, verbose_name='学校')),
                ('my_home', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户详细地址位置')),
                ('address', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户的故乡')),
                ('tel', models.CharField(blank=True, max_length=11, null=True, verbose_name='电话号码')),
                ('use_img', models.ImageField(default='images/infortx.png', upload_to='user_img', verbose_name='用户头像')),
            ],
            options={
                'verbose_name': '用户管理',
                'verbose_name_plural': '用户管理',
                'db_table': 'sp_user',
            },
        ),
        migrations.AddField(
            model_name='spaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Users', verbose_name='所属用户'),
        ),
    ]
